#ifndef GLMATRIXMODE_H
#define GLMATRIXMODE_H

enum GLMatrixMode {
    MATRIXMODE_MODEL_VIEW = 0x1700,
    MATRIXMODE_PROJECTION = 0x1701,
    MATRIXMODE_TEXTURE = 0x1702,
    MATRIXMODE_COLOR = 0x1800
};

#endif // GLMATRIXMODE_H
